package com.example.cocktails_fragment.model.remote.dto


/**
 * Specific drink dTO.
 *
 * @property dateModified
 * @property idDrink
 * @property strAlcoholic
 * @property strCategory
 * @property strCreativeCommonsConfirmed
 * @property strDrink
 * @property strDrinkAlternate
 * @property strDrinkThumb
 * @property strGlass
 * @property strIBA
 * @property strImageAttribution
 * @property strImageSource
 * @property strIngredient1
 * @property strIngredient10
 * @property strIngredient11
 * @property strIngredient12
 * @property strIngredient13
 * @property strIngredient14
 * @property strIngredient15
 * @property strIngredient2
 * @property strIngredient3
 * @property strIngredient4
 * @property strIngredient5
 * @property strIngredient6
 * @property strIngredient7
 * @property strIngredient8
 * @property strIngredient9
 * @property strInstructions
 * @property strInstructionsDE
 * @property strInstructionsES
 * @property strInstructionsFR
 * @property strInstructionsIT
 * @property strMeasure1
 * @property strMeasure10
 * @property strMeasure11
 * @property strMeasure12
 * @property strMeasure13
 * @property strMeasure14
 * @property strMeasure15
 * @property strMeasure2
 * @property strMeasure3
 * @property strMeasure4
 * @property strMeasure5
 * @property strMeasure6
 * @property strMeasure7
 * @property strMeasure8
 * @property strMeasure9
 * @property strTags
 * @property strVideo
 * @constructor Create empty Specific drink d t o
 */
data class SpecificDrinkDTO(
    val dateModified: String,
    val idDrink: String,
    val strAlcoholic: String,
    val strCategory: String,
    val strCreativeCommonsConfirmed: String,
    val strDrink: String,
    val strDrinkAlternate: Any,
    val strDrinkThumb: String,
    val strGlass: String,
    val strIBA: String,
    val strImageAttribution: String,
    val strImageSource: String,
    val strIngredient1: String,
    val strIngredient10: Any,
    val strIngredient11: Any,
    val strIngredient12: Any,
    val strIngredient13: Any,
    val strIngredient14: Any,
    val strIngredient15: Any,
    val strIngredient2: String,
    val strIngredient3: String,
    val strIngredient4: String,
    val strIngredient5: String,
    val strIngredient6: String,
    val strIngredient7: String,
    val strIngredient8: Any,
    val strIngredient9: Any,
    val strInstructions: String,
    val strInstructionsDE: String,
    val strInstructionsES: Any,
    val strInstructionsFR: Any,
    val strInstructionsIT: String,
    val strMeasure1: String,
    val strMeasure10: Any,
    val strMeasure11: Any,
    val strMeasure12: Any,
    val strMeasure13: Any,
    val strMeasure14: Any,
    val strMeasure15: Any,
    val strMeasure2: String,
    val strMeasure3: String,
    val strMeasure4: String,
    val strMeasure5: String,
    val strMeasure6: String,
    val strMeasure7: String,
    val strMeasure8: Any,
    val strMeasure9: Any,
    val strTags: String,
    val strVideo: Any
)
